### ISSUE TITLE
Demo notebook: "test_512_16bit.tfrecord" not found

### ISSUE THREAD

**Issue by hammoudiproject** [BrixIA/Brixia-score-COVID-19#11]
Dear authors,

Thank you for sharing your source code and datasets.

For your information, when deploying your demo notebook (test-singleimage.ipynb), we face an issue regarding a missing file named "test_512_16bit.tfrecord". Could you please guide us to fix this point?

Regards,
Karim

**Comment by msavardi** [comment]
Hi! 

Please refer to this solved issue: https://github.com/BrixIA/Brixia-score-COVID-19/issues/8 
If you still have doubt do not hesitate to ask! 😃

**Comment by HammoudiProj** [comment]
Hello, 

thank you for your reply. Besides, we did a meeting about your pipeline and colleagues and my-self have some other questions. We compiled them and my PhD student sent you an email two days ago. Thank you in advance for your responses. It will be very helpful.

Regards,
Karim

**Comment by HammoudiProj** [comment]
Dear Dr Savardi

Thank you for your assistance. Since our group needs to perform experiments, my PhD student sent you by email one key question about your dataset. Thank you in advance for your reply.

Regards,
Karim
