### ISSUE TITLE
How can I train the model?

### ISSUE THREAD

**Issue by gwang-kim** [BrixIA/Brixia-score-COVID-19#13]
Hi, thanks for your great works.

I want to know how to train the model, but I couldn't find the training code or any related instruction.
I can find only the instructions for preparing the dataset.
Can you share the training code?

**Comment by msavardi** [comment]
Sorry for my late reply, I missed your issue :( 

The training was quite straightforward, though. You can instantiate the BSNet model (see [here](https://github.com/BrixIA/Brixia-score-COVID-19/blob/master/src/BSNet/model.py)  ), and use a typical Keras training pipeline. If you need more support, please get in touch with me via email.
