### ISSUE TITLE
Missing weights

### ISSUE THREAD

**Issue by dougpsg** [BrixIA/Brixia-score-COVID-19#4]
Hi! Thank you for the code. 

I am trying to build the model but it seems that some weights are missing: "segmentation-model.h5" and "bscore-model.h5".
There is only "alignment-model.h5" in the "weights" folder. 

Thank you.

**Comment by msavardi** [comment]
FTR The model files will be publicly released after the scientific paper will be accepted.  In the meantime, those who are interested can contact us directly.
