### ISSUE TITLE
How to unzip?

### ISSUE THREAD

**Issue by neilbamb** [BrixIA/Brixia-score-COVID-19#5]
Hi Team,
 
The files have weird extensions like .aa, .ab, etc, and having a hard-luck trying to extract the images.
Can you please suggest the appropriate method or tool to extract it?

Thanks,
Neil

**Comment by msavardi** [comment]
Sorry for the late reply.

To unpack all the zipped archives, on unix-like system do:
1. Download all the files
2. From the command line call:  cat *.tar.gz.* | tar -xzv
3. A folder called dicom_clean will be created with all the unpacked files

Instead, for MS Window:
2. type *.tar.gz.* | tar xvfz -
