### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_applications'

### ISSUE THREAD

**Issue by datonefaridze** [BrixIA/Brixia-score-COVID-19#9]
it has problem importing module.
https://github.com/BrixIA/Brixia-score-COVID-19/blob/98463eb76707b401bab21cd029c51c367ba6cce1/src/BSNet/backbones/inception_resnet_v2.py#L37

**Comment by msavardi** [comment]
You may install this module with: `pip install Keras-Applications`. [Here](https://pypi.org/project/Keras-Applications/) additional details

**Comment by datonefaridze** [comment]
@msavardi thanks
